- README.md
added the simple run server command for the windows cmd to the readme.
> readme windows

- llama_cpp/server/app.py
Looks like these are supported now!
> Document presence frequency penalty

- Dockerfile.cuda
Give user option to specify exact CUDA image for more dynamic builds
> Change docker build dynamic param to image instead of cuda version

- examples/low_level_api/low_level_api_chat_cpp.py
fix low level example missing argument.
> fix "missing 1 required positional argument: 'min_keep'"

- README.md
Just pulled the latest and confirmed that metal is now, thanks!
> Document metal support

- llama_cpp/server/__main__.py
- llama_cpp/server/app.py
> fixes abetlen/llama-cpp-python #358

- README.md
- docs/macos_install.md
added a separete detailed MacOS Metal GPU install markdown page.
> Ianscrivener macos install md docs

- docs/install/macos.md
* Update "today" to version 0.1.62
* Fix numbering (there were 2 step 4's)
> Update macOS Metal GPU step 4

- README.md
added information from my research so far on how to make it run on phones
> added termux with root instructions

- llama_cpp/llama.py
- llama_cpp/llama_cpp.py
This adds bindings for https://github.com/ggerganov/llama.cpp/pull/2054
Tested with text-generation-webui (will link PR here soon)
> Add bindings for custom_rope

- README.md
- Added an example on how to set the variables `CMAKE_ARGS` and `FORCE_CMAKE`.
- Added a subtitle for the `Windows remarks` and `MacOS` remarks.
> Added info to set ENV variables in PowerShell

- README.md
Fixing OpenBLAS on Linux instructions as they are different now.
Source: https://github.com/ggerganov/llama.cpp#openblas
> Update install instructions for Linux OpenBLAS

- llama_cpp/llama_cpp.py
- add `mul_mat_q` parameter
- Update llama.cpp
> add `mul_mat_q` parameter

- setup.py
This enables Mypy and Pyright to check the typing.
PS: Thanks for creating this library!
> Add py.typed to conform with PEP 561

- README.md
> Fix dev setup in README.md so that everyone can run it

- docs/install/macos.md
Update instructions to download GGUF instead of GGML!
> Update instruction to download GGUF model in mac installation readme

- examples/low_level_api/low_level_api_llama_cpp.py
- examples/low_level_api/readme/low_level_api_llama_cpp.md
correction of some bug, deprecated function still here
> low level examples: bug fix

- llama_cpp/llama_chat_format.py
> Add MistralLite, Intel, and OpenChat prompt formats

- README.md
Documenting how to bind to `0.0.0.0` on servers.
> Documenting usage on server

- README.md
multi modal params fix: add logits = True -> to make llava work
> README.md multimodal params fix

- llama_cpp/llama_chat_format.py
> Update Pygmalion format

- llama_cpp/llama_chat_format.py
> add qwen chat format

- README.md
> Update README.md functionary demo typo

- llama_cpp/llama_chat_format.py
This change adds chat format for Saiga models (LLaMa based models for Russian language). See available models and more details at https://huggingface.co/collections/IlyaGusev/saiga2-saigamistral-6505d4ccc3d1e53166b636cd.
> Add Saiga chat format.

- llama_cpp/llama_grammar.py
Addresses https://github.com/abetlen/llama-cpp-python/issues/1051
> print_grammar to stderr

- llama_cpp/_utils.py
Instead of using a devnull to redirect stdout and stderr, used a dummy class with a 'write()' method that does nothing.
Closes #729
> Fix: fileno error google colab (#729)

- llama_cpp/_utils.py
Reverts abetlen/llama-cpp-python#1156
> Revert "Fix: fileno error google colab (#729)"

- llama_cpp/_internals.py
- llama_cpp/llama.py
- llama_cpp/llama_cpp.py
- llama_cpp/llava_cpp.py
- tests/test_llama.py
- Low level api calls now call directly into the loaded dll, not wrapped by a python function first. Reduces overhead however this now requires all low level calls to be **positional argument only** (this is type checked also).
- Use `NewType` to wrap opaque pointers like `ggml_context_p` and `ggml_model_p`, improves static type safety
> feat(low-level-api): Improve API static type-safety and performance

- docs/server.md
- examples/notebooks/Functions.ipynb
As mentioned in #1061, the function calling server readme is also needed to be updated.
This PR can be merged after the fix for #1181 is implemented.
> Update Functionary OpenAI Server Readme

- llama_cpp/llama_chat_format.py
There is a breaking bug in the functionary_v1_v2_handler such that it is not able to handle some chat requests as mentioned [here](https://github.com/MeetKai/functionary/issues/134). This is a result of wrong logic in the handler.
The following optimizations were done:
- Fixed the wrong logic (certain if-else statements were wrong)
- Changed the logic when `tool_choice="auto"`. In a while loop,
1. Generate function name first
2. Change the grammar according depending on whether the model chooses a function or not and generate the content
3. Check whether the model wants to generate another turn by checking for the presence of `\n<|from|>assistant`
4. Break out of the loop if stop token is generated
The second optimization allows for both text response and tool calls to be filled in 1 …
> Fix and optimize functionary chat handler

- llama_cpp/llama_chat_format.py
- llama_cpp/llama_grammar.py
Following this PR: https://github.com/abetlen/llama-cpp-python/pull/1347
> Update json to grammar

- examples/low_level_api/quantize.py
> fix quantize example

- .github/workflows/build-and-release.yaml
- .github/workflows/build-docker.yaml
- .github/workflows/publish-to-test.yaml
- .github/workflows/publish.yaml
- .github/workflows/test-pypi.yaml
- .github/workflows/test.yaml
Bump  actions/checkout@v3 to v4 (Deprecated)
Bump action/setup-python@v4 to v5 (Deprecated)
> Workflow update

- .github/workflows/build-and-release.yaml
> Fix build-and-release.yaml

- llama_cpp/llama.py
Special tokens are already mapped from metadata by llama.cpp
> Remove unnecessary metadata lookups

- examples/ray/README.md
- examples/ray/llm.py
- examples/ray/requirements.txt
This could be used as a starting point for people who want to experiment with distributed LLM inference on Ray
> example: LLM inference with Ray Serve

- llama_cpp/llama_types.py
> fix: make content not required in ChatCompletionRequestAssistantMessage

- .github/workflows/build-wheels-cuda.yaml
I have obtained this change from [ExLlamaV2](https://github.com/turboderp-org/exllamav2/tree/master/.github/workflows), and it has fixed [my llama-cpp-python workflows](https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions), which were having the same mamba errors as the ones here.
> Fix the CUDA workflow
