abetlen/llama-cpp-python

.gitignore
examples/high_level_api/fastapi_server.py
llama_cpp/server/__main__.py
setup.py

Wow. It took awhile to figure out that mlock was silently causing the model to fail without an exception. 😢 haha
It's awesome once I got it working though. I still need to look into where it puts the built library and where it searches for it. I think it's searching in the same directory as the executable, but I might have had to manually move it around to get it happy. Don't know why this is.
Summary:
1. Added `pydantic` as a dependency in `setup.py`. The code was previously throwing errors when `pydantic` was not present.
❗ This might also need to be done for scikit-build. I installed it manually at the very start. You probably know more about the best place to do it.
2. Set the default value of `n_batch` to 8 in both `examples/high_level_api/fastapi_server.py` and …

Fixes and Tweaks to Defaults

---

examples/low_level_api/common.py
examples/low_level_api/low_level_api_chat_cpp.py

Implements
- Use mmap option and argument
- Verbose prompt argument
- IterSearch which prevents the instruction prefix from being echoed
- Ignore EOS option
- Fixes a bug that causes exactly 1 character to be printed before the instruction break kicks in
Ignore EOS option hopefully fixes https://github.com/abetlen/llama-cpp-python/issues/59

Low level chat: Added iterative search to prevent instructions from being echoed

---

llama_cpp/llama_cpp.py

Sometimes its nice to try different library versions and different forks of llama etc (given they still use the same api).
This commit adds the local path as the first place to search for llama libraries.

Allow local llama library usage

---

setup.py

* When compiling and installing on a Chinese language Windows system, the following error occurs, because the default encoding of the Windows system of Chinese language is "GBK" instead of "UTF-8", and specifying the "UTF-8" encoding directly when reading the file can solve this problem. https://github.com/abetlen/llama-cpp-python/issues/45
```
Traceback (most recent call last):
File "C:\Users\Xpk22\miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
main()
File "C:\Users\Xpk22\miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
json_out['return_val'] = hook(**hook_input['kwargs'])
File "C:\Users\Xpk22\miniconda3\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.p …
```

Add UTF-8 Encoding in read_text.

---

examples/low_level_api/common.py
examples/low_level_api/low_level_api_chat_cpp.py

Fixes https://github.com/abetlen/llama-cpp-python/issues/79
I forgot to tokenize the end of text message.
Also fixes "n_predict" which didnt handle -1 before, but does now.

Fix TypeError in low_level chat

---

examples/low_level_api/low_level_api_chat_cpp.py
examples/low_level_api/low_level_api_llama_cpp.py
llama_cpp/llama.py
tests/test_llama.py

https://docs.python.org/3/library/codecs.html#error-handlers
This detects a multibyte UTF8 character, and doesn't return if its incomplete.
If there otherwise wasn't enough tokens or the model somehow returns invalid bytes, we use errors="ignore" to remove invalid characters.
Ascii example:
> 'German ß, ♬'.encode(encoding='ascii', errors="ignore")
> b'German , '
But there will never be thrown a decode or encode error.
Fixes:
https://github.com/abetlen/llama-cpp-python/issues/36
https://github.com/abetlen/llama-cpp-python/issues/57
https://github.com/abetlen/llama-cpp-python/issues/100
https://github.com/abetlen/llama-cpp-python/issues/116

Fix UnicodeDecodeError permanently

---

.dockerignore
.github/workflows/build-docker.yaml
.github/workflows/publish.yaml
Dockerfile
README.md

Add Dockerfile

---

.github/workflows/publish.yaml
Dockerfile
README.md

Fixes #70
This PR adds a Dockerfile and updates the release workflow to build the latest Docker image too. Both amd64 and arm64 arches are built.

Add Dockerfile + build workflow

---

Dockerfile

Slim-Bullseye based docker image

---

examples/high_level_api/fastapi_server.py

Split this in case these two implementations exist for a reason, but this depends on https://github.com/abetlen/llama-cpp-python/pull/125. Really its just the one commit at the end.
I found it confusing that two fastapi servers exist in this repo (more detail https://github.com/Stonelinks/llama-cpp-python/issues/2)
So this PR "deprecates" the example by pointing folks at the module one, but still remaining runnable.

Deprecate example server

---

README.md

llama.cpp does not read BLAS related environment variables while configuring build with CMake. 
Instead, it needs to be passed as command line argument which correctly configures BLAS backend. It can be done by setting `CMAKE_ARGS` environment variable.

Updated installation instructions for BLAS backends

---

llama_cpp/llama.py
llama_cpp/server/app.py

The /v1/embeddings route of OpenAI api allows a string or a list of string as input.
This updates allows the of /v1/embeddings to mimic the OpenAI's one.

feat: make embedding support list of string as input

---

examples/low_level_api/low_level_api_chat_cpp.py

low level Chat.py and low_level_api_chat_cpp.py do not output the antiprompt when end of text is reached. Example below.  Without the fix, sometimes the antiprompt is output. Most times not.
The fix appends the antiprompt to embd when the end of text input token is received.
--
USER: Can I ask a question?               
ChatLLaMa: Of course! Please go ahead with your question.
Can I ask another question?
ChatLLaMa: Yes, you can ask as many questions as you like.
USER:

low_level_api_chat_cpp.py: Fix missing antiprompt output in chat.

---

examples/low_level_api/low_level_api_chat_cpp.py

from_bytes is missing the required byte_order.  Though perhaps from_bytes should not be used for this multi-byte check

fix "from_bytes() missing required argument 'byteorder'"

---

llama_cpp/server/app.py

As far as I can see, adding support for the mirostat settings was a simple matter of defining their fields in the api request router code; the Llama code already supports it.

Added mirostat support for completions, chat completions API

---

llama_cpp/llama.py
llama_cpp/server/app.py

I was inspired by the way [simpleaichat](https://github.com/minimaxir/simpleaichat/blob/main/PROMPTS.md) works and I wanted to try running it on my own hardware with my own API server. This code relies on the `logit_bias` parameter to work, so I needed to add it.
The way OpenAI's API works is that the `logit_bias` is a mapping from `input_ids` (as a string) to a bias (as a float). Because of the need to use IDs instead of just the token strings themselves, then it means this parameter and its functionality is tied to ChatGPT's tokenizer. This is a problem for other models, obviously.
So in addition to implementing the API as OpenAI intended, I also added another parameter that changes the meaning of `logit_bias` to be a mapping from token strings (as a string) to a bias (as a float).
I …

Add support for `logit_bias` and `logit_bias_type` parameters

---

llama_cpp/llama.py

Should help understand by how many tokens it exceeds the context size

Update llama.py: Added how many input tokens in ValueError exception

---

llama_cpp/llama.py

Based on the discussion in #398, I was able to make `Llama.eval` faster by only calling `np.concatenate` once all the batches are done.
Performance measurements based on the [tester](https://github.com/abetlen/llama-cpp-python/issues/398#issue-1762827269) included in the original issue.
Master: (~3137.75ms overhead)
```py
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
501    2.977    0.006   87.771    0.175 llama.py:400(eval)
```
This PR: (~350.9ms overhead)
```py
ncalls  tottime  percall  cumtime  percall filename:lineno(function)
501    0.041    0.000   84.657    0.169 llama.py:400(eval)
```

Only concatenate after all batches are done

---

llama_cpp/llama.py

Thanks for the wonderful Python wrapper for llama.cpp.
When using your framework, I found a problem in `output['logprobs']['token_logprobs]`.
For example, on commit ca11673 (latest main branch when I write this) the following code
```python
llama = Llama('.../llama.cpp/models/30B/ggml-model-q8_0.bin', logits_all=True)
print(llama('I', temperature=0, max_tokens=5, logprobs=1))
```
will output `{'id': 'cmpl-caa5cef2-ae2f-4157-8323-2dc644bb6308', 'object': 'text_completion', 'created': 1688724957, 'model': '/data/yi/llama.cpp/models/30B/ggml-model-q8_0.bin', 'choices': [{'text': "'m a big fan", 'index': 0, 'logprobs': {'tokens': ["'", 'm', ' a', ' big', ' fan'], 'text_offset': [1, 2, 3, 5, 9], 'token_logprobs': [-19.985351200841283, -19.405950866756548, …

Fix incorrect token_logprobs (due to indexing after sorting)

---

llama_cpp/llama.py
llama_cpp/server/app.py

The current llama-cpp-python does not include support for --tensor-split parameter. When running a large model across two GPUs, it currently loads the model by default in a half-by-half manner. However, this approach presents certain issues. For example, when a user has two GPUs with different VRAM sizes, it can lead to OOM. Implementing the --tensor-split parameter will address this problem by empowering users to define the proportion of the model distributed across multiple GPUs.
I'm uncertain if importing ctypes into llama.py is the most appropriate approach. However, I'm currently unsure of an alternative solution in llama_cpp.py. I would greatly appreciate any advice or suggestions regarding this matter.
Tested thouroughly with text-generation-webui. I'll sumbit a PR there after this …

Add support for llama.cpp's --tensor-split parameter

---

llama_cpp/llama.py
llama_cpp/server/app.py

I've added a `RouteErrorHandler` that wraps any exception raised by the server into an OpenAI-like error response.
For example, n_ctx(2048) with a prompt max_tokens=1 for 2049 tokens over 2048, you might get a json error response with status code 400 like the one below. 
```json
{
"error": {
"message": "This model's maximum context length is 2048 tokens, however you requested 2050 tokens (2049 in your prompt; 1 for the completion). Please reduce your prompt; or completion length.",
"type": "invalid_request_error",
"param": "messages",
"code": "context_length_exceeded"
}
}
```
This friendly message should help you determine how many prompt tokens you need to remove and resend.
I also removed the `le` option from the `max_tokens` field to account for the removal of the 2048 token limit with …

Added `RouteErrorHandler` for server

---

llama_cpp/llama_cpp.py

Improve handling of failure when the model fails to load, see https://github.com/abetlen/llama-cpp-python/issues/488#issuecomment-1647728733`

raise exception when `llama_load_model_from_file` fails

---

README.md
llama_cpp/llama.py

Add support for llama2 70b (uses `n_gqa` parameter)
See https://github.com/abetlen/llama-cpp-python/issues/488#issuecomment-1647728733 and https://github.com/ggerganov/llama.cpp/pull/2276

Llama2 70b support

---

README.md

Changed "7B" to "70B" in _loading llama-2 70b_ section.

Fix typo in model path

---

llama_cpp/llama.py

[Llama.cpp changed its tensor_split from an array to a pointer](https://github.com/ggerganov/llama.cpp/commit/ae178ab46bfd6ecb2422da5dad441a4e2fef8b7e) 4 days ago, so our implementation doesn't work anymore. 
I updated the code to make it work.

Update tensor_split to match llama.cpp's change

---

docker/openblas_simple/Dockerfile

Current build produces the following:
`RuntimeError: Failed to load shared library '/usr/local/lib/python3.11/site-packages/llama_cpp/libllama.so': /usr/local/lib/python3.11/site-packages/llama_cpp/libllama.so: undefined symbol: cblas_sgemm`

Fix OpenBLAS Docker build

---

README.md

Main repository README has a spelling error of "lowe-level API". It should be "low-level API".
Pretty minor change, but increases the quality of the README.

Fix typo "lowe-level API" to "low-level API" in the README

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py
llama_cpp/llama_grammar.py

Recently, [grammar based sampling](https://github.com/ggerganov/llama.cpp/pull/1773) was merged into llama.cpp.
However, there's no explicit parser API we can currently use in Python. Therefore, I translated the grammar-parser.cpp into llama_grammar.py.
I've tested it using `vendor/llama.cpp/grammars/json.gbnf,` and the output of parsed grammar was perfectly the same as compiled version. See the example below. I hope this will help implementing function call someday!
Test code:
```python
from llama_cpp.llama import Llama
llm = Llama(
model_path="./models/llama-7B/ggml-model.bin",
grammar="./vendor/llama.cpp/grammars/json.gbnf",
)
print(llm(prompt="")["choices"][0]["text"])
```
Output:
```
ggml_init_cublas: found 1 CUDA devices:
Device 0: NVIDIA GeForce RTX 4070 Ti, compute capability 8.9 …
```

Add grammar-based sampling

---

llama_cpp/llama_grammar.py

It should compare between enum and enum, not enum and enum.value.
This can lead to grammar printing problem.

Fix typos in llama_grammar

---

docker/cuda_simple/Dockerfile

PR for the issue: https://github.com/abetlen/llama-cpp-python/issues/597
Previously models produced garbage output when running on GPU with layers offloaded.

Fixed Cuda Dockerfile

---

docker/README.md

- Add `--gpus:all` parameter to CuBLAS to avoid `The NVIDIA Driver was not detected. GPU functionality will not be available` error while running `cuda_simple`
- Move CuBLAS Nvidia support note under `cuda_simple`
- Use Markdown extensions for notes (important, note, etc.)
- Remove _USE_ sections at the end
- Readability improvements (use third-level heading mostly)
Rendered version: https://github.com/Isydmr/llama-cpp-python/tree/main/docker

Docker improvements

---

README.md
llama_cpp/llama.py
llama_cpp/llama_cpp.py
pyproject.toml
tests/test_llama.py

GGUF support for llama.cpp Closes #628 
Currently works to update your old ggml v3 llama models run
```
python3 vendor/llama.cpp/convert-llama-ggmlv3-to-gguf.py --input <path-to-ggml> --output <path-to-gguf>
```
TODO

GGUF (Breaking Change to Model Files)

---

llama_cpp/llama.py

Missing CJK characters is caused by decoding incomplete bytes. This PR shows a way to fix it, hope it can be a reference.

Fix CJK and emoji stream output

---

README.md
examples/low_level_api/low_level_api_chat_cpp.py
examples/low_level_api/low_level_api_llama_cpp.py

This fixes the documentation of the low-level API in `README.md` and in the `examples` folder.
`llama_init_from_file`, for example, was replaced by `llama_load_model_from_file` in https://github.com/abetlen/llama-cpp-python/commit/952228407ebd68ef621ad747e3561c821d1c02d3

Fix low level api examples

---

llama_cpp/server/app.py
pyproject.toml

Add X-Request-ID request header for mirroring custom IDs.

---

llama_cpp/server/app.py

Original OpenAI endpoint contains useful header for measuring pure processing time in ms.
This helps to avoid additional network delay, geo locality overhead time into final measurements.

Adds openai-processing-ms response header

---

llama_cpp/llama.py

Fix rope scaling defaults
- Defaults were previously 1 for `rope_freq_base` and 10000 for `rope_freq_base`, these are now both 0 for defaults.
https://github.com/ggerganov/llama.cpp/pull/3401
Edit: Removed the backwards compatibility so that there is never any unintended behavior with those settings later.

Fix rope scaling defaults

---

llama_cpp/llama.py

When GPU acceleration is not properly configured, or some other cases, if the user tries to split tensors into multiple GPUs, **model load** will exit with an exception of
`Could not load Llama model from path: ../models/codellama-7b.Q4_K_M.gguf. Received error invalid index (type=value_error)`
This error message is caused by expanding a python list into a smaller C array `llama.py:312`
However, the error message is misleading, which doesn't contain detail enough information.
Thus this PR captures this case and raise a human-readable exception to point out the situation. Feel free to make any improvements.

Add validation for tensor_split size exceeding LLAMA_MAX_DEVICES

---

llama_cpp/llama_chat_format.py

This PR fix a bug that cause repeated greeting from chatbot which is described in #801 .  After this fix, the prompt passed to llama.cpp will have correct `[INST]` and `[/INST]` around user inputs and generate reaonable response.
Note this fix relates to #781.  The new formatting template recently introduced seems to have multiple issues.    Thanks @teleprint-me for pointing this out and guide the discussion.

Fix repeat greeting

---

llama_cpp/llama.py

Make use of suppress_stdout_stderr when freeing model

---

llama_cpp/server/app.py

The check for `n_gpu_layers` parameter for the llama_cpp server should be ">=-1".
Closes Issue #823.

#823 update value check for n_gpu_layers field

---

llama_cpp/llama.py

When `stream == True` the branch with the `yield` statement that contains the `finish_reason` isn't visited when `remaining_tokens` is empty.
Moved the `yield` statement containing `finish_reason` after the loop over `remaining_tokens`. This branch is always visited when `stream == True`.
Fixes #735

Fix streaming doesn't return finish reason

---

llama_cpp/server/app.py

Created this small PR which just adds a `grammar` parameter to the `completions` endpoint, therefore closing #778 . Of course this violates OpenAI's API definition, but the parameter is optional. Here's an example for it to test (use the json.gnbf from `llama.cpp`):
```
import json
import requests
if __name__ == "__main__":
prompt = "Please provide me with a valid JSON that encodes the following " \
"Address: Testine Testerson, 420 Imaginary St, 12345 Star City, USA. " \
"Make sure yu respect data types and only use one per field. "
print("######")
print("# WITHOUT GRAMMAR")
print("######")
res = requests.post(
url="http://localhost:8000/v1/completions",
json={
"prompt" : f"<s>[INST]{prompt}[/INST]",
"stop" : ["</s>"],
"max_tokens" : 256,
"stream" : True,
"temperature" : 0.9
}, …
```

Grammar support for Web Server

---

llama_cpp/llama.py

We discovered that it was possible to exploit  `Llama._create_completion` suffix parameter to send string-like object which could actually lead to Arbitrary Code Execution.
Here is PoC: https://github.com/tangledgroup/llama-cpp-python-exploit/blob/f99baf1e66b9fa79987c594179ac93eadfb2ca97/exploit.py#L45

fixed Llama._create_completion suffix check

---

llama_cpp/server/app.py

This prevents to iterate over the whole vocabulary each decoding step.

Iterate over tokens that should be biased rather than the entire vocabulary.

---

llama_cpp/llama.py

This fixes an exception that I consistently see with oobabooga's TGWUI:
```
Traceback (most recent call last):
File "/home/cebtenzzre/src/forks/text-generation-webui/modules/llamacpp_model.py", line 42, in __del__
File "/home/cebtenzzre/src/forks/llama-cpp-python/llama_cpp/llama.py", line 1720, in __del__
File "/home/cebtenzzre/src/forks/llama-cpp-python/llama_cpp/llama.py", line 1712, in _free_model
TypeError: 'NoneType' object is not callable
Exception ignored in: <function Llama.__del__ at 0x7f55471987c0>
Traceback (most recent call last):
File "/home/cebtenzzre/src/forks/llama-cpp-python/llama_cpp/llama.py", line 1720, in __del__
File "/home/cebtenzzre/src/forks/llama-cpp-python/llama_cpp/llama.py", line 1712, in _free_model
TypeError: 'NoneType' object is not callable
```
\_\_del\_\_ …

llama: fix exception in Llama.__del__

---

README.md
llama_cpp/llama_cpp.py

I noticed that the library .dll file that gets installed in python site-packages location is actually libllama.dll while it is trying to look for llama.dll in the code in windows machine. After making this change and reinstalling from source, everything started working fine for me.
Also updated README.md to include some extra info for Windows users trying to build using w64devkit like llama.cpp.
Setup: Windows 10 Pro, Intel CPU i7 12th gen.
Issues related: #568 #825 #751

Fix for shared library not found and compile issues in Windows

---

llama_cpp/llama.py
llama_cpp/server/app.py
tests/test_llama.py

It should behave like llama.cpp, where most out of the box usages treat special characters accordingly. See https://github.com/abetlen/llama-cpp-python/issues/838#issuecomment-1784966013 for more details.
I checked that with this fix, the vanilla call to `llm.create_completion(temperature=0)` leads to exactly the same results for a simple chat prompt than when using `./main --temp 0` from `llama.cpp` - which it didn't before.
I changed the behaviour also for the embeddings and the LlamaTokenizer. I'm missing context so might be wrong on those, but I figured it would be good to be consistent.

fix: tokenization of special characters:

---

llama_cpp/llama_grammar.py
tests/test_grammar.py

The `LlamaGrammar.grammar` attribute is written by `init()`, but that method always returns `None`, so `__init__()` would then discard the previously written object.
Note that `Llama.generate()` will call `LlamaGrammar.reset()` before using the grammar, so it will also work fine without this change, but `Llama.sample()` does not call the `reset()` method.

Do not set `grammar` to `None` for new `LlamaGrammar` objects

---

llama_cpp/llama_chat_format.py

I found this cool project doesn't support baichuan2, so I make this PR to support it.
I added a new chat format named "baichuan-2" to support baichuan2 chat model.
I only tested **Baichuan2-7B-Chat**. Not sure whether Baichuan2-13B-Chat can work.
1. convert baichuan2 mode to baichuan1
> see: https://github.com/baichuan-inc/Baichuan2
replace the lm_head.weight with new one.
2. uses llama.cpp's convert.py to convert **Baichuan2-7B-Chat** to GGUF format.
```
python3 convert.py --outfile models/baichuan-2-7b-chat-baichuan-f16.gguf ../baichuan/Baichuan2-7B-Chat-Baichuan/
```
3. quantize the model, take Q3_K_M for example.
```
./quantize models/baichuan-2-7b-chat-baichuan-f16.gguf models/baichuan-2-7b-chat-baichuan-Q3_K_M.gguf Q3_K_M
```
4. launch llama-cpp-python server and test. remember to …

Add chat format to support baichuan2

---

llama_cpp/llama_chat_format.py

Similar to https://github.com/abetlen/llama-cpp-python/pull/936, but support baichuan 1 (https://huggingface.co/baichuan-inc/Baichuan-13B-Chat)
launch llama-cpp-python server with " --chat_format baichuan"
```
python3 -m llama_cpp.server --model models/baichuan-13b-chat-baichuan-Q3_K_M.gguf --host 0.0.0.0 --port 9000 --n_gpu_layers -1 --chat_format baichuan
```

Add chat format to support baichuan

---

llama_cpp/llama_chat_format.py

The string assignment for `system_message` was broken into two parts without proper concatenation. 
This change concatenates these two string parts properly.

fix: Typo in the Open Orca chat format #874

---

llama_cpp/llama.py

See #990. This change makes the logits_to_logprobs function equivalent to the version in the llama.cpp repository. It uses numpy so it's much faster than the previous version.
*Edit:* I should add that I'm not 100% confident in this change. I'd appreciate if someone else could test this themselves too.

Replace logits_to_logprobs implementation with numpy equivalent to llama.cpp

---

llama_cpp/llama.py
pyproject.toml
tests/test_llama.py

The [implementation in main](https://github.com/abetlen/llama-cpp-python/blob/8e44a32075de4aba2fc9877d4a2a34a0e7314c0d/llama_cpp/llama.py#L2282-L2290) (from [this PR](https://github.com/abetlen/llama-cpp-python/pull/991)) only works for 1-D logits. It silently fails for 2-D or 3-D logits. The implementation in this PR works out-of-the-box for 1-D, 2-D, and 3-D logits. (3-D is possible in the future w/ batch inference and `logits_all=True`.) This feature might be useful b/c there are [some](https://github.com/abetlen/llama-cpp-python/blob/8e44a32075de4aba2fc9877d4a2a34a0e7314c0d/llama_cpp/llama.py#L1785-L1787) places in the code where we can save time by vectorizing / not converting data to lists. I'll do that in a future PR.
The minimal and sufficient fix is to set `axis=-1` in the …

Fix logits_to_logprobs for 2-D and 3-D logits

---

llama_cpp/llama.py

If the ```n_ctx``` parameter is set to 0 the function should use the maximum context length of the selected model, but it didn't work. There was a problem with the initialization of this parameter and a related problem with ```n_batch```.
I know that the code is not the best one, but in order to get the model information about the context I needed to add it after the creation of the model instance at line 923 of the file  ```llama.py```.
```python
self._model = _LlamaModel(
path_model=self.model_path, params=self.model_params, verbose=self.verbose
)
``` 
Unfortunately, different objects were already initialized, therefore in the fix I had to change the ```n_ctx```, ```self.n_batch```, ```self.context_params.n_ctx``` and ```self.context_params.n_batch``` variables even if they already had …

Bug fixed with n_ctx=0

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py
llama_cpp/server/app.py

Adds the `offload_kqv` setting to the context settings fields struct and removes the `f16_kv`. Leaving `f16_kv` there caused a null pointer exception when attempting to use the embeddings example script:
```
$ python examples/high_level_api/high_level_api_embedding.py --model ../../llama/models/llama-2-7b.Q5_K_M.gguf
...
ValueError: NULL pointer access
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
File "/home/brandon/src/llama-cpp-dev/llama-cpp-python/examples/high_level_api/high_level_api_embedding.py", line 11, in <module>
print(llm.create_embedding("Hello world!"))
File "/home/brandon/src/llama-cpp-dev/llama-cpp-python/llama_cpp/llama.py", line 1309, in create_embedding
data.append(
SystemError: <method 'append' of 'list' …
```

WIP: Complete removal or f16_kv, add offload_kqv field

---

llama_cpp/llama.py

Follow-up to #1002
Run this in an `ipython` shell (`python -m pip install jupyter` if you don't have it already)
```python
import numpy as np
_scores: np.ndarray = -np.random.default_rng(123).uniform(
low=0, high=60, size=(20, 32_000)
)
token_offset = 1
print("time old")
%timeit [Llama.logits_to_logprobs(row.tolist()) for row in _scores][token_offset:]
print()
print("time new")
%timeit Llama.logits_to_logprobs(_scores)[token_offset:]
```
prints
```
time old
72.6 ms ± 862 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
time new
24.5 ms ± 142 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
```python
import numpy as np
_scores: np.ndarray = -np.random.default_rng(123).uniform(
low=0, high=60, size=(20, 32_000)
) …
```

Don't convert logprobs arrays to lists

---

examples/low_level_api/low_level_api_llama_cpp.py

Two small changes to make the low level example run successfully:
* Updated call to `llama_cpp.llama_n_vocab` to pass model instead of context
* Combined previous `llama_sample_repetition_penalty` and `llama_sample_frequency_and_presence_penalties` into `llama_sample_repetition_penalties` with keyword arguments
Thank you!

Update low level example to match current API

---

llama_cpp/llama_cpp.py

Using the functions llama_kv_cache_view_update and llama_kv_cache_view_free causes a crash. The root cause is a discrepancy between the ctypes definition and the actual definition of the C functions. For example,
```python
def llama_kv_cache_view_free(view: llama_kv_cache_view):
"""Free a KV cache view. (use only for debugging purposes)"""
return _lib.llama_kv_cache_view_free(view)
_lib.llama_kv_cache_view_free.argtypes = [llama_kv_cache_view]         # <--- This is the struct itself
```

Fix ctypes definitions of `llama_kv_cache_view_update` and `llama_kv_cache_view_free`.

---

llama_cpp/server/app.py

This pull request adds optional API key authentication to the llama-cpp-python server, aligning with OpenAI API standards. A new command-line option --api_key API_KEY has been introduced to enable this feature. When the API key is provided, all server requests require authentication for enhanced security. If the API key is not set, the server operates without authentication, ensuring backward compatibility.

Implement openai api compatible authentication

---

llama_cpp/llama.py

Hi, this is fix for text_offset of multi-token characters.
For example, "おはようございます" will be tokenized to
and a character "ざ" is composed of 3 tokens.
In non-stream case, text_offset is calculated from token_str's length, which will zero if token is not valid unicode, and so "ざ" is ignored and text_offset is not aligned with text.
This PR fixes it by using the same way as stream case, which detokenizes entire completion_tokens to calculate text's length.
It also fixes stream case's bug which calculates length of bytes instead of length of characters.
before
```
"prompt": "おはよう"
"text":"ございます！\n\nI’m back from my"
"text_offset":[4,5,5,5,5,6,7,8,9,10,11,12,13,14,19,24]
"tokens":["ご","","","","い","ま","す","！","\n","\n","I","’","m"," back"," from"," my"]
```
after
```
"prompt": "おはよう" …
```

fix text_offset of multi-token characters

---

README.md

In Llama.create_chat_completion, the `tool_choice` property does not have an s on the end.
Fixing this minor typo to keep the docs up to date with the API.

Fix: Correct typo in README.md

---

llama_cpp/llama.py

Let's a user pass in the penalize_nl param to the generate function and passes that to the sample function instead of always using the previous default value of `True`

add ability to pass in penalize_nl param

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py
llama_cpp/server/model.py
llama_cpp/server/settings.py

Quick implementation of KV overrides which accepts strings in llama.cpp `--kv_overrides KEY=TYPE:VALUE ..` format. For example `llama.expert_used_count=int:3`  Multiple overrides may be space separated.
Not that familiar with ctypes or the preferred types to use here.
Closes #1084

Implement GGUF metadata KV overrides

---

llama_cpp/server/app.py

Addresses : #1083 
This would allow the endpoint to accept both `Accept` headers, `application/json` and `text/event-stream`.
Response model for the SSE response is left as str, i dont think openapi currently has mechanism to specify model for each events currently and using the list of chunk type might conflict if the client code is generated. 
OpenAI allows `Accept: text/event-stream`, but does not use it as a flag for stream. It needs to be provided explicitly as a parameter to POST.

Support Accept text/event-stream in chat and completion endpoints

---

llama_cpp/server/settings.py

This PR updates the OpenAI API server's command line arguments to allow passing `--n_ctx 0` as a command-line argument. Currently, `--n_ctx` parameter has a minimum of `1`: in `llama_cpp/server/settings.py` you can see the following context CLI parameter configuration: `n_ctx: int = Field(default=2048, ge=1, description="The context size.")`
As of `llama-cpp-python@0.2.24`, per #1015 by @DanieleMorotti, passing `n_ctx=0` to the `LLama` class in `llama_cpp/llama.py` automatically sets the `n_ctx` to the model's `n_ctx_train` paramter from KV, and also updates the model's `n_batch` to `min(n_ctx, n_batch)`. This is intentional to allow `llama-cpp-python` to infer the context size from the GGUF model file's KV parameters. 
However, when this change was made, the OpenAI API server's CLI …

fix(cli): allow passing n_ctx=0 to openAI API server CLI arguments

---

README.md

we've had a llamaindex integration with llama.cpp + llama-cpp-python for a few months now (https://docs.llamaindex.ai/en/stable/examples/llm/llama_2_llama_cpp.html), and would love to highlight in README! 
feel free to suggest other places to put this

add llamaindex integration to readme

---

llama_cpp/llama.py

(starting from a clean branch)
76aafa6 didn't work for me, `_kv_overrides_array[i]` refs uninitialised `i` and I think it's necessary to instantiate the CStructs array with `()` or it ends up a generic PyCArrayType.
Let me know what you think about this PR instead.
Simple validation that it takes effect:
```
>>> llm=llama_cpp.Llama(model_path="../models/mixtral-8x7b-instruct-v0.1.Q6_K.gguf", kv_overrides={"llama.embedding_length":4095})
validate_override: Using metadata override (  int) 'llama.embedding_length' = 4095
llama_model_load: error loading model: invalid n_rot: 128, expected 127 
```

GGUF metadata KV overrides, re #1011

---

llama_cpp/llama_chat_format.py
llama_cpp/llama_types.py

Adds Anyscale-style json schema mode for all simple chat formats (ie chatml, llama2, alpaca, vicuna, etc) as well as llava multimodal models. Source https://docs.endpoints.anyscale.com/guides/json_mode/
This is using the python openai API but any REST client will work.
```python
import openai
client = openai.OpenAI(
base_url="http://localhost:8000/v1", api_key="esecret_YOUR_API_KEY"
)
chat_completion = client.chat.completions.create(
model="mistralai/Mixtral-8x7B-Instruct-v0.1",
messages=[
{
"role": "system",
"content": "You are a helpful assistant that outputs in JSON.",
},
{"role": "user", "content": "Who won the world series in 2020"},
],
response_format={
"type": "json_object",
"schema": {
"type": "object",
"properties": {"team_name": {"type": "string"}},
"required": ["team_name"],
}, …
```

Add json schema mode

---

llama_cpp/_internals.py
llama_cpp/llama.py
llama_cpp/llama_chat_format.py
llama_cpp/server/settings.py

Closes #1096 
Okay so for now this is going to be the behaviour / priority of the automatic chat format detection
1. Use provided `chat_handler` param
2. Use provided `chat_format` param
3. If model has a gguf `chat_template` try to string match it against known jinja2 templates and use the matching template's eos token
4. If model has a gguf `chat_template` use `eos_token` for stop generation
5. Use llama 2 chat format

Automatically set chat format from gguf

---

CMakeLists.txt

When using LLaVa, CLIP does not load on the default backend (i.e. CUDA/Metal when they are available). This arises because the code in `clip.cpp` conditions on `GGML_USE_XXX` rather than `LLAMA_USE_XXX`. The main `llama.cpp` CMake file enables the former when the latter is present, but we need to do it manually for LLaVA since we're bypassing the top level.

Use proper backend for CLIP

---

README.md

If incorrect compiler is set (such as `/usr/bin/c++`), the compilation will fail. This change proposes the correct steps to compile with sycl support on Intel Arc GPUs.

[README] Set the correct command for compiling with sycl support

---

llama_cpp/llama_tokenizer.py

commit 901827013b732d74f1f67033062d13a6204a62bd introduced a cyclic dependency within Llama objects. That change causes old models to linger in memory longer than necessary, thereby creating memory bloat in most applications attempting to switch between models at runtime. This patch simply removes the problematic line, allowing models to deallocate without relying on GC. One might also consider combining `weakref.ref` with a `@property` if the `llama` attribute is absolutely necessary to expose in the tokenizer class.

Allow Llama objects to be freed earlier again

---

llama_cpp/_internals.py
llama_cpp/llama.py

Now that `llama.cpp` supports BERT embedding models (https://github.com/ggerganov/llama.cpp/pull/5423), this modifies `embed` / `create_embedding` to truncate and combine inputs to fit into the model context size and allows for efficient high-volume embedding. I tried to be minimal with changes, and am definitely open to alternate suggestions. What we have now:
* Add `reset` and `add_sequence` methods to `_LlamaBatch` to make multi-sequence batches
* Tokens are truncated to `n_ctx` by default, and without truncation an error is thrown if `n_tokens > n_ctx`
* Embeddings are normalized by default but this can be turned off
One could eke out some gains from grouping batches more intelligently, but I wanted to keep it simple.

Batch embed strings to fit model context

---

llama_cpp/llama.py

Made some fixes to the pooling layer in `llama.cpp` that are reflected here. Previously we had to divide by the number of tokens in the sequence. Now we can just take them as-is and optionally normalize. Also changed the truncation to `n_batch` rather than `n_ctx` since that's what we're writing to.
Embedding numbers now match up very closely with SentenceTransformers. Usually around `1-(1e-7)` cosine similarity, though there are some remaining issues with tokenizing text with accents.

Incorporate embedding pooling layer fixes

---

llama_cpp/server/app.py

this fixes compatibility with some OpenAI clients, including BetterChatGPT (https://github.com/ztjhz/BetterChatGPT/issues/537). i'm not sure if this will cause problems with other clients. i'm also working with the client to see if they are willing to handle these separators more gracefully.

switch to '\n' for EventSourceResponse separator

---

README.md
docs/api-reference.md
llama_cpp/llama.py

Adds the ability to pull models directly from huggingface hub via a `from_pretrained` method on the `Llama` class. You'll need to `pip install huggingface-hub` to use this feature.
```python
import llama_cpp
llama = llama_cpp.Llama.from_pretrained(
repo_id="Qwen/Qwen1.5-0.5B-Chat-GGUF",
filename="*q8_0.gguf",
verbose=False
)
response = llama.create_chat_completion(
messages=[
{
"role": "user",
"content": "What is the capital of France?"
}
],
response_format={
"type": "json_object",
"schema": {
"type": "object",
"properties": {
"country": {"type": "string"},
"capital": {"type": "string"}
},
"required": ["country", "capital"],
}
},
stream=True
)
for chunk in response:
delta = chunk["choices"][0]["delta"]
if "content" not in delta:
continue
print(delta["content"], end="", flush=True)
print() …
```

feat: Pull models directly from huggingface

---

llama_cpp/llama_chat_format.py

This PR adds the recently released Google's Gemma formatting, so that it can be used via the `chat_format` arg within the `Llama` class i.e. `chat_format="gemma"`.
More information about the models in the following HuggingFace Collection at https://huggingface.co/collections/google/gemma-release-65d5efbccdbb8c4202ec078b
_Note that some of the current GGUF versions uploaded to the HuggingFace Hub are not working fine with `llama.cpp`, but I got it working when using e.g. https://huggingface.co/rahuldshetty/gemma-7b-it-gguf-quantized/blob/main/gemma-7b-it-Q4_K_M.gguf._
```python
llm = Llama(
model_path="./models/gemma-7b-it-Q4_K_M.gguf",
chat_format="gemma",
n_gpu_layers=-1,
)
print(
llm.create_chat_completion(
messages=[
{"role": "user", "content": "What's the …
```

Add Google's Gemma formatting via `chat_format="gemma"`

---

README.md

Without the single quotes, when running the command, an error is printed saying no matching packages found on pypi. Adding the quotes fixes it
```bash
$ pip install llama-cpp-python[server]
zsh: no matches found: llama-cpp-python[server]
```
Fix found the llama.cpp repo in [comments](https://github.com/ggerganov/llama.cpp/discussions/795#discussioncomment-6226069) is to use this command `pip install 'llama-cpp-python[server]'`

Update README.md to fix pip install llama cpp server

---

llama_cpp/llama_chat_format.py

Currently in main Mixtral will not work reliably for chat completions because the slightly different Mixtral chat format string is not detected in the metadata, so this adds the right string and checks that too so it can then use the existing format_mistral_instruct method which does seem to work well enough. 
I think this should help make using Mixtral more obvious.
I suspect this will address #1202 
@abetlen

Detect Mixtral's slightly different format

---

README.md
llama_cpp/server/model.py
llama_cpp/server/settings.py

Adds ability to pull model from huggingface model hub to the server.
CLI
```
python3 -m llama_cpp.server --hf_model_repo_id Qwen/Qwen1.5-0.5B-Chat-GGUF --model '*q8_0.gguf'
```
Config File
```json
{
"host": "0.0.0.0",
"models": [
{
"model": "qwen1_5-0_5b-chat-q8_0.gguf",
"hf_model_repo_id": "Qwen/Qwen1.5-0.5B-Chat-GGUF"
}
]
}
```
If using multiple models in a config file, models will not be pulled until they are requested, this may cause long requests or timeouts.

Add server support for hf pull

---

llama_cpp/llama.py

The token strings were not correctly retrieved (empty).
Closes #1228

Fix eos/bos_token for Jinja2ChatFormatter

---

README.md

The example uses `embeddings=True`, but it should actually be `embedding=True`.

Fix typo in README.md embeddings example

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py

Due to updates in https://github.com/ggerganov/llama.cpp/pull/5796, sequence level embeddings are now output through a separate channel from token level embeddings, and they are accessed with `llama_get_embeddings_seq`.

Switch embed to llama_get_embeddings_seq

---

llama_cpp/llama_chat_format.py

The following code,
```py
from llama_cpp.llama_chat_format import Llava15ChatHandler
Llava15ChatHandler(clip_model_path='this-path-does-not-exist')
```
When ran aborts and yields a core dump.
```
$ python3 main.py
Aborted (core dumped)
```
This PR installs a more graceful exception with an informative error message.

Check for existence of clip model path

---

llama_cpp/llama_chat_format.py

- Adds new variables `tools`, `tool_choice`, `function_call` and `functions` to jinja template.
- Adds support for function / tool calling response to all chat formats when making explicit function calls (not auto)

Add tools/functions variables to Jinja2ChatFormatter

---

CMakeLists.txt

Fixes https://github.com/abetlen/llama-cpp-python/issues/1285
See https://github.com/ggerganov/llama.cpp/commit/381da2d9f0940d7009e3e918bed36338c8ff2fbb

set LLAMA_METAL_EMBED_LIBRARY=on on MacOS arm64

---

llama_cpp/llama.py
llama_cpp/llama_chat_format.py
llama_cpp/llama_types.py
llama_cpp/server/app.py
llama_cpp/server/types.py

Hi, this pull request is my small update/modification to add logprobs and top_logprobs arguments when creating chat completion request into llama cpp server (align with OpenAI API template).
Sample request:
POST https://host:port/v1/chat/completions
{
"model": "mixtral-8x7b",
"messages": [
{
"role": "system",
"content": "You are a helpful assistant."
},
{
"role": "user",
"content": "Hello! Could you help me plan for 3-day trip in Hanoi?"
}
],
"logprobs": true,
"top_logprobs": 1,
"max_tokens": 1024,
"temperature": 0.0001,
"stream": false
}
Could you help me to review it? Thanks ^^

Add logprobs return in ChatCompletionResponse

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py
llama_cpp/server/model.py
llama_cpp/server/settings.py

https://github.com/abetlen/llama-cpp-python/discussions/1220
https://github.com/abetlen/llama-cpp-python/issues/1305

add KV cache quantization options

---

README.md

Having API documentation references to a local server which may not be available yet (to those who are just evaluating) can be confusing.

Changed local API doc references to hosted

---

llama_cpp/_internals.py

**Bug:** currently all previous tokens are passing to `llama_sample_repetition_penalties` function instead of last `penalty_last_n` tokens.
**Description:** `llama_sample_repetition_penalties` function expects last `penalty_last_n` tokens. But it gets all previously generated tokens which leads to the algorithm not working correctly.
As you can see in the code below it will use only first `penalty_last_n` tokens to create `token_count` dict:
```
...
// Create a frequency map to count occurrences of each token in last_tokens
std::unordered_map<llama_token, int> token_count;
for (size_t i = 0; i < penalty_last_n; ++i) {
token_count[last_tokens[i]]++;
}
...
```
This behavior is obviously incorrect which in our case led to the case where our model had a lot of answers with repetitions.
Also …

fix last tokens passing to sample_repetition_penalties function

---

llama_cpp/llama.py
llama_cpp/server/settings.py

This PR changes the default `n_threads_batch` parameter of `Llama` instances to use all available CPU cores. Currently, the default behaviour is to use half of all cores, which is optimal for text generation, but is suboptimal for batch processing. This change should provide some speed improvements, most notably on CPU / OpenBLAS / Metal.

Use all available CPUs for batch processing

---

llama_cpp/llama.py

Was looking at making the llama context more compact so that could store a cache for a large # of documents.
- Only store up to `n_tokens` logits instead of full `(n_ctx, n_vocab)` sized array.
- Difference between ~350MB and ~1500MB for example prompt with ~300 tokens vs. context size of 4096.
- Auto-formatting changes
- Can back these out if not desired
Q: Do we need to store `Llama.scores` when logits are already saved on the `llama_context` struct?  This ~doubles the size of `LlamaState`, but I tried reloading directly using `get_logits` and the two were not the same (not sure why, think it could be repetition penalty applied to `Llama.scores`?  There wasn't a logits_bias or `logits_processor` being applied AFAICT).

Make saved state more compact on-disk

---

llama_cpp/server/app.py
llama_cpp/server/settings.py

for backward compatibility, this is false by default. it can be set to true to disable EventSource pings which are not supported by some OpenAI clients. fixes https://github.com/abetlen/llama-cpp-python/issues/1256

add `disable_ping_events` flag

---

llama_cpp/llama_chat_format.py

This PR adds support for the recently-released Llama-3 models by Meta. Specifically this chat format is used for their [`Instruct` pretrained models](https://huggingface.co/meta-llama/Meta-Llama-3-70B-Instruct).
Model card: https://github.com/meta-llama/llama3/blob/main/MODEL_CARD.md
See reference implementation for the chat format: https://github.com/meta-llama/llama3/blob/main/llama/tokenizer.py#L202-L229

Add Llama-3 chat format

---

pyproject.toml

The `scikit-build-core` build dependency was broken with version `0.9.1`, this change enforces the build to use the new release with the fix from:
- https://github.com/scikit-build/scikit-build-core/issues/718
Closes #1366

Update `scikit-build-core` dependency CMake error

---

llama_cpp/server/settings.py

I actually have been using llama-cpp-python server in AWS Lambda functions for some time now. While the default behavior of only allocating half the cpu threads by default is wise, especially considering you may have a multi-user operation occurring and don't want to potentially lock things up, when it comes to single-tenant systems like Lambda, that concern is mitigated.
However, no original functionality is changed. If the user runs llama-cpp-python server today, with their current configurations, they should get the same experience as they have previously. However, if the user specifies `n_threads` or `n_threads_batch` as -1, then similar to the `n_gpu_layers` it will default to using all available listed by multiprocessing.cpu_count(). This is especially effective when using AWS …

Provide ability to dynamically allocate all available CPU threads without affecting prior functionality

---

README.md
llama_cpp/_internals.py
llama_cpp/llama.py
llama_cpp/llama_cpp.py
llama_cpp/llama_types.py

Getting embeddings direct from "non-embedding" LLMs is pretty important for achieving SOTA performance (see [MTEB Leaderboard](https://huggingface.co/spaces/mteb/leaderboard)). This PR makes it so that the embed functions return token level embeddings when the `pooling_type` ends up being `LLAMA_POOLING_TYPE_NONE` and the appropriate sequence level embeddings otherwise. After that, the user can do whatever type of pooling they wish. This should address most of the concerns raised in #1288 too.
There are still some gotchas. If you request mean/cls pooling on a model that doesn't support it, it will hard crash in `llama.cpp`. And it's hard to know ex ante what types of pooling a model supports. So it's probably just better to wait until this gets sorted out in `llama.cpp`.
Also, this …

Allow for possibly non-pooled embeddings

---

README.md
llama_cpp/llama_chat_format.py

- Implement tracking of number of completion tokens (Closes #1344 )
- Fixes the bug that resulted in both `function_call` and `tool_calls` returning function/tool calls. Now, when `tools` are provided and function calls are invoked, only `tool_calls` will return the calls while `function_call` will be None, vice versa for `functions`. (Addresses [this issue](https://github.com/MeetKai/functionary/issues/156))
- Fixes functionary chat handler incompatibility with Python 3.8 (Closes #1361 )
- Adjusted README
Streaming implementation in progress currently and will be in a future PR.

Functionary bug fixes

---

llama_cpp/llama_grammar.py

Use Python's built-in UTF-8 handling to get code points, as `const_char_p` currently steps through characters, not bytes. 
Closes #1349

Fix UTF-8 handling with grammars

---

llama_cpp/server/model.py

I noticed that even though setting `flash_attn` to `true` in my model config file, `llama.cpp` kept reporting `llama_new_context_with_model: flash_attn = 0`. This super-small PR fixes that - turns out the setting wasn't passed on to the model loader.

Fix: Propagate flash attn to model loader

---

llama_cpp/llama_chat_format.py

**Features**
- Set up streaming for functionary-v2 chat handler
- Raises error if users use functionary-v1
- Returns only 1 function/tool call if `functions` is provided and >= 1 if `tools` is provided
**Bug Fixes**
- Fix `function-call={...}` always converted to `auto` bug

Implement streaming for Functionary v2 + Bug fixes

---

llama_cpp/llama.py

Currently the log prints `None`.

Fix chat_format log

---

llama_cpp/llama_chat_format.py

Looks like in all cases where `stream == False` the `create_completion` function was missing the new args.
I was getting this error when querying functionary v2 on llama-cpp-server:
```
TypeError: create_completion() missing 2 required positional arguments: 'prompt' and 'grammar'
```

adding missing args in create_completion for functionary chat handler

---

llama_cpp/llama_chat_format.py

Chat templates are rendered with `ImmutableSandboxedEnvironment` in `transformers` so no need to do otherwise here.

Render templates in immutable sandbox

---

llama_cpp/llama.py

In llama_cpp/llama.py, the eval function converts return value of `self._ctx.get_logits()`, which is a CtypesArray, to list then copy it into `self.scores`. Here the CtypesArray is directly converted to a numpy array which speeds up the conversion and copying. The speed-up is especially noticeable on smaller models with faster inference time.

Improve Llama.eval efficiency

---

CMakeLists.txt

When compiling for the HIP SDK version 5.7 on Windows I get the following error.
```
CMake Error at C:/Users/Engininja2/AppData/Local/Temp/tmptb9uvli3/build/cmake_install.cmake:241 (file):
file INSTALL cannot find "C:/Program Files/AMD/ROCm/5.7/bin/amdhip64.dll":
File exists.
```
AMD's CMake files have CMake looking in the SDK for amdhip64.dll but it's included with the gpu driver in C:\Windows\System32
This PR avoids including it and other runtime dlls when compiled for HIP.

Disable Windows+CUDA workaround when compiling for HIPBLAS

---

llama_cpp/_internals.py
llama_cpp/llama.py
llama_cpp/llama_chat_format.py
tests/test_llama_chat_format.py

Having multiple BOS can ruin generation, this would occur in several ways, usually through user adding them unnecessarily, in this case output a warning if we detect two in a row.
However, several formats/templates also have BOS in them, and we would add another one later in completion, therefore tokenize format/template prompts before completion to avoid this.
Added a new `added_special` property to `ChatFormatterResponse` to detect when BOS/EOS has already been added to prompt.
Also added missing `token_cls`, `token_sep`, ~~`add_bos_token` and `add_eos_token`~~ to `_LlamaModel` because I thought I needed them (turns out I didn't).
Fixes #1501

Avoid duplicate special tokens in chat formats

---

CMakeLists.txt
Makefile
README.md
llama_cpp/llama.py
llama_cpp/server/model.py
llama_cpp/server/settings.py

This PR include those changes:
- Add `rpc_servers` to `Llama`, to bypass the `rpc_servers` to llama.cpp lib
- In Makefile, add item to enable `LLAMA_RPC` flag
- Update the llama.cpp submodule reference to latest version
Tested on my machine, work as expected
Closes #1455

Feat: adding `rpc_servers` parameter to `Llama` class

---

examples/high_level_api/high_level_api_infill.py
llama_cpp/_internals.py
llama_cpp/llama.py

Add `spm_infill` option to perform infill in the Suffix/Prefix/Middle pattern instead of Prefix/Suffix/Middle as some models (like the new `Codestral`) prefer this.
Also added a tokenizer hack to remove leading space in suffix to improve inference, tested on several different tokenizers/vocabs with success.

Support SPM infill

---

llama_cpp/_internals.py
llama_cpp/llama.py
llama_cpp/server/model.py

This PR introduces a `close` method to `Llama` and `_LlamaModel`, allowing users to explicitly free the model from RAM/VRAM.
The previous implementation relied on the destructor of `_LlamaModel` to free the model. However, in Python, the timing of destructor calls is unclear: for instance, the `del` statement does not guarantee immediate invocation of the destructor.
This PR offers an explicit method to release the model, which works immediately and enables the user to load another model without encountering memory issues. Here is an example:
```python
llama = Llama(...)
...
llama.close()
```
Additionally, this PR allows the the `Llama` class class to be used as a context manager via the `contextlib.closing` interface. Here is an example:
```python
from …
```

Add methods to explicitly free model from memory

---

README.md

Qwen2 generally outperforms Qwen1.5 according to released [benchmarks](https://huggingface.co/Qwen/Qwen2-1.5B-Instruct):
| Datasets | Qwen1.5-0.5B-Chat | Qwen2-0.5B-Instruct |
| --- | --- | --- |
| MMLU | 35.0 | 37.9 |
| HumanEval | 9.1 | 17.1 |
| GSM8K | 11.3 | 40.1 |
| C-Eval | 37.2 | 45.2 |
| IFEval (Prompt Strict-Acc.) | 14.6 | 20.0 |
This model is working fine for me, and I would expect it to generally provide a better experience for users exploring this package. I would expect speed to be nearly identical given the similar sizes of these two models.

Update readme examples to use newer Qwen2 model

---

.github/workflows/build-wheels-cuda.yaml

This pins Visual Studio and Windows Server to specific past versions, avoiding a recent update that broke compatibility with CUDA 12.1.
Confirmed to be working on my llama-cpp-python-cuBLAS-wheels fork: https://github.com/oobabooga/llama-cpp-python-cuBLAS-wheels/actions/runs/9651433295/job/26619287975
Closes #1543

Fix the CUDA workflow

---

llama_cpp/server/model.py

One of the parameters, `split_mode`, was not used when loading. Fix it by passing it to the Llama server.

Actually use split_mode from model settings

---

llama_cpp/llama_types.py

:wave: @abetlen - thanks for this lib!
just adding the 'required' literal to match https://github.com/openai/openai-python/blob/main/src/openai/types/chat/chat_completion_tool_choice_option_param.py#L12

Add 'required' literal to ChatCompletionToolChoiceOption

---

docker/simple/Dockerfile

Currently if you pull the latest image and run, you will face, No such file error due to a filepath change in last commit
`@mashuk999 ➜ /workspaces/llama-cpp-python (main) $ docker run -it ghcr.io/abetlen/llama-cpp-python:latest
Unable to find image 'ghcr.io/abetlen/llama-cpp-python:latest' locally
latest: Pulling from abetlen/llama-cpp-python
f11c1adaa26e: Pull complete 
f2856587ea65: Pull complete 
3633d497474f: Pull complete 
a49add4e8750: Pull complete 
a503d964c760: Pull complete 
3a1a379ae865: Pull complete 
e2df0e42496e: Pull complete 
4f4fb700ef54: Pull complete 
a6bcd4dec1a1: Pull complete 
8bbda24c4a05: Pull complete 
eb190ca62661: Pull complete 
b38e68be4046: Pull complete 
Digest: sha256:fdd7ef0bfbca0a68a918d71c49cb85d5630a418dcfa1484fcb1b854b5f7bd1d7
Status: Downloaded newer …

Fix for broken docker image - llama-cpp-python:latest

---

llama_cpp/llama.py

Fix : Runtime erors. Non-existent variables   _stack and _lora_adapter were being accessed for destruction.
Closes #1631

Fix : Runtime errors

---

llama_cpp/_internals.py

Upstream changed some things w/ how grammar works in https://github.com/ggerganov/llama.cpp/pull/8508 and https://github.com/ggerganov/llama.cpp/pull/8093 - may also want to check if `llama_grammar_init` return value is null, since this is what's done now rather than throwing an error. 
Old argument order for `llama_grammar_accept_token` was:
llama_grammar_accept_token(ctx, grammar, token)
Now this is:
llama_grammar_accept_token(grammar, ctx, token)
Can test with
```python
model = llama_cpp.Llama("bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/Meta-Llama-3.1-8B-Instruct-Q8_0.gguf", n_ctx=4096, n_gpu_layers=-1, offload_kqv=True, n_batch=1024, n_threads=12, n_threads_batch=12, verbose=True)
model.create_chat_completion(
messages=[
{
"role": "system",
"content": "You are a helpful assistant that …
```

Fix crash when using grammar

---

llama_cpp/llama_cpp.py
llama_cpp/llama_grammar.py

https://github.com/ggerganov/llama.cpp/pull/6640
https://github.com/ggerganov/llama.cpp/pull/6467
https://github.com/ggerganov/llama.cpp/pull/7194
Fixes #1547

Ported back new grammar changes from C++ to Python implementation

---

llama_cpp/llama.py

The number of `prompt_tokens` to eval is an import message.

Add more detailed log for prefix-match

---

llama_cpp/llama.py

Models that are not located at the top-level of hugging face repos are not found. Thus, this PR enables recursive ls of offs.
Enables now:
```python
Llama.from_pretrained(
"LiteLLMs/OpenELM-270M-GGUF", filename="*/Q2_K-00001-of-00001.gguf",
subfolder="Q2_K"
)   
```
which would otherwise fail with:
```
ValueError: No file found in LiteLLMs/OpenELM-270M-GGUF that match */Q2_K-00001-of-00001.gguf
Available Files:
["Q2_K", "Q3_K", "Q3_K_L", "Q3_K_M", "Q3_K_S", "Q4_0", "Q4_1", "Q4_K", "Q4_K_M", "Q4_K_S", "Q5_0", "Q5_1", "Q5_K", "Q5_K_M", "Q5_K_S", "Q6_K", "Q8_0", ".gitattributes"]
```

Enable recursive search of `HFFS.ls`

---

llama_cpp/llama.py

Before this PR, `Llama._create_completion: cache saved` was printed to stderr even if verbose mode was disabled.
After this PR, that message is only printed to stderr if verbose mode is enabled.

fix: only print 'cache saved' in verbose mode

---

pyproject.toml

When I ran tests using this command:
```shell-session
pip install -e ".[test]"
python -m pytest
```
I got this error message:
```python
def test_llama_server():
>       from fastapi.testclient import TestClient
E       ModuleNotFoundError: No module named 'fastapi'
tests/test_llama.py:246: ModuleNotFoundError
```
This PR adds the missing dependencies for the test feature.

Missing dependencies for test

---

llama_cpp/llama.py

`Llama.close` didn't free the LoRA, but `Llama.__del__` does. This PR moves the freeing of the LoRA to the `ExitStack` that we already use to free the model, context, and other resources.
Additionally, this PR moves the initialization of the `ExitStack` to the top of `__init__`, ensuring that `_stack` is always present. As a result, we no longer need to check whether `_stack` exists or is `None`.

Fix Llama.close didn't free lora adapter

---

llama_cpp/_internals.py
llama_cpp/llama.py
llama_cpp/llama_tokenizer.py

I noticed that it was not possible to detokenize special tokens, such as the EOS token, when using Phi-3(.1). This PR makes sure that the `special` flag can be passed to the `detokenize()` method of both the `LlamaTokenizer` and the `LlamaHFTokenizer`
I also noticed that `prev_tokens` was not being used in the detokenize method of `LlamaTokenizer`, so this PR also adds that functionality based on `LlamaHFTokenizer`

Enable detokenizing special tokens

---

llama_cpp/llama.py

This PR changes the type hint of the `logit_bias` parameter from `Optional[Dict[str, float]]` to `Optional[Dict[int, float]]`. (It was already being cast to int, the logic does not change, only the type hint was wrong which was confusing)

Fix type hint for `logit_bias` parameter

---

llama_cpp/llama_cpp.py

The `llama_eval` function was removed in 0.2.14 (0d37ce5) but the docs still reference it. Updated some of the docs in `llama_cpp.py` to match the `llama.h` docs from upstream.
_Note: the `examples/low_level_api/*.py` files still reference `llama_eval` and therefore don't work anymore, but I haven't looked into fixing these._

docs: Remove ref to llama_eval in llama_cpp.py docs

---

llama_cpp/server/app.py
llama_cpp/server/errors.py

`server.create_chat_completion` would not close the exit_stack if an exception happened while calling `llama.create_chat_completion`.
This PR fixes #1759 and is a superset of #1795.

fix: added missing exit_stack.close() to /v1/chat/completions

---

Makefile
llama_cpp/llama_chat_format.py
llama_cpp/llama_types.py

The OpenAI compatible server should match the response structure of the OpenAI API for chat completions. Unfortunately there is a discrepancy with the format of logprobs: we return the logprobs format for the completions API, rather than the *chat* completions API.
This PR:
- updates the types to match the OpenAI API
- adds a function `_convert_text_completion_logprobs_to_chat` which is used in the chat completion responses to convert the logprobs to the new API format
- updates the documentation on running the server locally, as I discovered this was outdated when I went to test things out
Fixes #1787

fix: chat API logprobs format

---

llama_cpp/server/app.py

Fixes missing await statements from code merges before merge of PR #1798
Due to missing await statement `create_chat_completion` endpoint currently fails. This PR fixes this by adding the appropriate await.
It also changes 2 `exit_stack.close()` to the appropriate await `exit_stack.aclose()`

fix: add missing await statements for async exit_stack handling

---

llama_cpp/llama.py
llama_cpp/llama_cpp.py

This PR addresses the issue reported here: https://github.com/abetlen/llama-cpp-python/issues/1830 - After the 0.3.0 update, [llama_perf_context_print() ](https://github.com/ggerganov/llama.cpp/blob/3edfa7d3753c29e44b964c0ff424d2ea8d5fdee6/src/llama.cpp#L10049)failed to correctly display inference time, tokens per second, and other related data. 
After some investigation, I found that this change: https://github.com/abetlen/llama-cpp-python/commit/f8fcb3ea3424bcfba3a5437626a994771a02324b, caused this issue due to a commit in the upstream llama.cpp repo: https://github.com/ggerganov/llama.cpp/commit/0abc6a2c25272d5cf01384dda8ee8bfec4ba8745. When designing the `no_perf` parameter, although it defaults to **false**, it is set to **true** in the …

Fix error showing time spent in llama perf context print

---

llama_cpp/llama.py

Fix typo in variable name: replace `op_offloat` with `op_offload` in llama.py (v0.3.14), that caused `AttributeError` during model copying
Steps to Reproduce:
```python
from copy import copy, deepcopy
model = Llama.from_pretrained(
repo_id='bartowski/google_gemma-3-1b-it-GGUF',
filename='google_gemma-3-1b-it-Q8_0.gguf',
verbose=False,
)
deepcopy(model)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
[/tmp/ipython-input-119572725.py](https://localhost:8080/#) in <cell line: 0>()
8     verbose=False,
9 )
---> 10 deepcopy(model)
1 frames
[/usr/lib/python3.11/copy.py](https://localhost:8080/#) in deepcopy(x, memo, _nil)
159                     reductor = …
```

fix: rename op_offloat to op_offload in llama.py
